-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 10:08:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zspmovie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zspmovie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zspmovie` DEFAULT CHARACTER SET utf8 ;
USE `zspmovie` ;

-- -----------------------------------------------------
-- Table `zspmovie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zspmovie`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `is_admin?` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zspmovie`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zspmovie`.`film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zspmovie`.`user_has_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zspmovie`.`user_has_film` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `film_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `film_id`),
  CONSTRAINT `fk_user_has_film_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zspmovie`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_film_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `zspmovie`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
